# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Util
version:      0.09
version_from: Util.pm
installdirs:  perl
requires:
    Math::Complex:                 0
    Test::Deep:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
